# Generated by Django 5.1.7 on 2025-03-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="name",
            field=models.CharField(default="Unnamed Product", max_length=40),
            preserve_default=False,
        ),
    ]
